Backend/DenunciaEficiente/config/routes.rb
Rails.application.routes.draw do
  resources :witness_evidences
  resources :witnesses
  resources :evidences
  resources :complaints
  resources :police_units
  resources :incidents
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#index'

  post 'user_token' => 'user_token#create'
  get 'users/current' => 'users#current'
  resources :users

  namespace :api, defaults: {format: 'json'} do
    resources :users, :incidents, :police_units, :complaints, :evidences, :witnesses, :witness_evidences, only: [:index, :create, :destroy, :update, :show]
  end
end

Backend/DenunciaEficiente/app/controllers/api/witnesses_controller.rb
class Api::WitnessesController < ApplicationController
    before_action :set_incident, only: [:show, :update, :destroy]
   
    def index
      @witnesses = Witness.all
      render json: @witnesses
    end
   
    def show
      render json: @witness
    end
   
    def create
      @witness = Witness.new(incident_params)
   
      if @witness.save
        render json: @witness, status: :created
      else
        render json: @witness.errors, status: :unprocessable_entity
      end
    end
   
    def update
      if @witness.update(incident_params)
        render json: @witness, status: :ok
      else
        render json: @witness.errors, status: :unprocessable_entity
      end
    end
   
    def destroy
      @witness.destroy
      head :no_content
    end
   
    private
      def set_incident
        @witness = Witness.find(params[:id])
      end
   
      def incident_params
        params.require(:witness).permit(:user_id, :complaint_id)
      end
end

Backend/DenunciaEficiente/app/controllers/witnesses_controller.rb
class WitnessesController < ApplicationController
  before_action :set_incident, only: [:show, :update, :destroy]
 
  def index
    @witnesses = Witness.all
    render json: @witnesses
  end
 
  def show
    render json: @witness
  end
 
  def create
    @witness = Witness.new(incident_params)
 
    if @witness.save
      render json: @witness, status: :created
    else
      render json: @witness.errors, status: :unprocessable_entity
    end
  end
 
  def update
    if @witness.update(incident_params)
      render json: @witness, status: :ok
    else
      render json: @witness.errors, status: :unprocessable_entity
    end
  end
 
  def destroy
    @witness.destroy
    head :no_content
  end
 
  private
    def set_incident
      @witness = Witness.find(params[:id])
    end
 
    def incident_params
      params.require(:witness).permit(:name, :description, :incidence_father_id)
    end
end

Backend/DenunciaEficiente/app/helpers/witnesses_helper.rb
module WitnessesHelper
end

Backend/DenunciaEficiente/app/views/witnesses/_form.html.erb
<%= form_with(model: witness, local: true) do |form| %>
  <% if witness.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(witness.errors.count, "error") %> prohibited this witness from being saved:</h2>

      <ul>
      <% witness.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :complaint_id %>
    <%= form.text_field :complaint_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Backend/DenunciaEficiente/app/views/witnesses/edit.html.erb
<h1>Editing Witness</h1>

<%= render 'form', witness: @witness %>

<%= link_to 'Show', @witness %> |
<%= link_to 'Back', witnesses_path %>

Backend/DenunciaEficiente/app/views/witnesses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Witnesses</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Complaint</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @witnesses.each do |witness| %>
      <tr>
        <td><%= witness.user_id %></td>
        <td><%= witness.complaint_id %></td>
        <td><%= link_to 'Show', witness %></td>
        <td><%= link_to 'Edit', edit_witness_path(witness) %></td>
        <td><%= link_to 'Destroy', witness, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Witness', new_witness_path %>

Backend/DenunciaEficiente/app/views/witnesses/new.html.erb
<h1>New Witness</h1>

<%= render 'form', witness: @witness %>

<%= link_to 'Back', witnesses_path %>

Backend/DenunciaEficiente/app/views/witnesses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @witness.user_id %>
</p>

<p>
  <strong>Complaint:</strong>
  <%= @witness.complaint_id %>
</p>

<%= link_to 'Edit', edit_witness_path(@witness) %> |
<%= link_to 'Back', witnesses_path %>