Backend/DenunciaEficiente/config/routes.rb
Rails.application.routes.draw do
  resources :witness_evidences
  resources :witnesses
  resources :evidences
  resources :complaints
  resources :police_units
  resources :incidents
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#index'

  post 'user_token' => 'user_token#create'
  get 'users/current' => 'users#current'
  resources :users

  namespace :api, defaults: {format: 'json'} do
    resources :users, :incidents, :police_units, :complaints, :evidences, :witnesses, :witness_evidences, only: [:index, :create, :destroy, :update, :show]
  end
end

Backend/DenunciaEficiente/app/models/incident.rb
class Incident < ApplicationRecord
end

Backend/DenunciaEficiente/app/controllers/api/incidents_controller.rb
class Api::IncidentsController < ApplicationController
    before_action :set_incident, only: [:show, :update, :destroy]
   
    def index
      @incidents = Incident.all
      render json: @incidents
    end
   
    def show
      render json: @incident
    end
   
    def create
      @incident = Incident.new(incident_params)
   
      if @incident.save
        render json: @incident, status: :created
      else
        render json: @incident.errors, status: :unprocessable_entity
      end
    end
   
    def update
      if @incident.update(incident_params)
        render json: @incident, status: :ok
      else
        render json: @incident.errors, status: :unprocessable_entity
      end
    end
   
    def destroy
      @incident.destroy
      head :no_content
    end
   
    private
      def set_incident
        @incident = Incident.find(params[:id])
      end
   
      def incident_params
        params.require(:incident).permit(:name, :description, :incidence_father_id)
      end
end

Backend/DenunciaEficiente/app/helpers/incidents_helper.rb
module IncidentsHelper
end

Backend/DenunciaEficiente/app/views/incidents/_form.html.erb
<%= form_with(model: incident, local: true) do |form| %>
  <% if incident.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(incident.errors.count, "error") %> prohibited this incident from being saved:</h2>

      <ul>
      <% incident.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :incident_father_id %>
    <%= form.text_field :incident_father_id %>
  </div>

  <div class="field">
    <%= form.label :created_at %>
    <%= form.datetime_select :created_at %>
  </div>

  <div class="field">
    <%= form.label :updated_at %>
    <%= form.datetime_select :updated_at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Backend/DenunciaEficiente/app/views/incidents/edit.html.erb
<h1>Editing Incident</h1>

<%= render 'form', incident: @incident %>

<%= link_to 'Show', @incident %> |
<%= link_to 'Back', incidents_path %>

Backend/DenunciaEficiente/app/views/incidents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Incidents</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Incidence father</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @incidents.each do |incident| %>
      <tr>
        <td><%= incident.name %></td>
        <td><%= incident.description %></td>
        <td><%= incident.incident_father_id %></td>
        <td><%= incident.created_at %></td>
        <td><%= incident.updated_at %></td>
        <td><%= link_to 'Show', incident %></td>
        <td><%= link_to 'Edit', edit_incident_path(incident) %></td>
        <td><%= link_to 'Destroy', incident, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Incident', new_incident_path %>

Backend/DenunciaEficiente/app/views/incidents/new.html.erb
<h1>New Incident</h1>

<%= render 'form', incident: @incident %>

<%= link_to 'Back', incidents_path %>

Backend/DenunciaEficiente/app/views/incidents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @incident.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @incident.description %>
</p>

<p>
  <strong>Incidence father:</strong>
  <%= @incident.incident_father_id %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @incident.created_at %>
</p>

<p>
  <strong>Updated at:</strong>
  <%= @incident.updated_at %>
</p>

<%= link_to 'Edit', edit_incident_path(@incident) %> |
<%= link_to 'Back', incidents_path %>