Backend/DenunciaEficiente/config/routes.rb
Rails.application.routes.draw do
  resources :witness_evidences
  resources :witnesses
  resources :evidences
  resources :complaints
  resources :police_units
  resources :incidents
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#index'

  post 'user_token' => 'user_token#create'
  get 'users/current' => 'users#current'
  resources :users

  namespace :api, defaults: {format: 'json'} do
    resources :users, :incidents, :police_units, :complaints, :evidences, :witnesses, :witness_evidences, only: [:index, :create, :destroy, :update, :show]
  end
end

Backend/DenunciaEficiente/app/models/evidence.rb
class Evidence < ApplicationRecord
end

Backend/DenunciaEficiente/app/controllers/api/evidences_controller.rb
class Api::EvidencesController < ApplicationController
    before_action :set_evidence, only: [:show, :update, :destroy]
   
    def index
      @evidences = Evidence.all
      render json: @evidences
    end
   
    def show
      render json: @evidence
    end
   
    def create
      @evidence = Evidence.new(evidence_params)
   
      if @evidence.save
        render json: @evidence, status: :created
      else
        render json: @evidence.errors, status: :unprocessable_entity
      end
    end
   
    def update
      if @evidence.update(evidence_params)
        render json: @evidence, status: :ok
      else
        render json: @evidence.errors, status: :unprocessable_entity
      end
    end
   
    def destroy
      @evidence.destroy
      head :no_content
    end
   
    private
      def set_evidence
        @evidence = Evidence.find(params[:id])
      end
   
      def evidence_params
        params.require(:evidence).permit(:complaint_id, :path_file, :narration)
      end
end

Backend/DenunciaEficiente/app/controllers/evidences_controller.rb
class EvidencesController < ApplicationController
  before_action :set_evidence, only: [:show, :edit, :update, :destroy]

  # GET /evidences
  # GET /evidences.json
  def index
    @evidences = Evidence.all
  end

  # GET /evidences/1
  # GET /evidences/1.json
  def show
  end

  # GET /evidences/new
  def new
    @evidence = Evidence.new
  end

  # GET /evidences/1/edit
  def edit
  end

  # POST /evidences
  # POST /evidences.json
  def create
    @evidence = Evidence.new(evidence_params)

    respond_to do |format|
      if @evidence.save
        format.html { redirect_to @evidence, notice: 'Evidence was successfully created.' }
        format.json { render :show, status: :created, location: @evidence }
      else
        format.html { render :new }
        format.json { render json: @evidence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /evidences/1
  # PATCH/PUT /evidences/1.json
  def update
    respond_to do |format|
      if @evidence.update(evidence_params)
        format.html { redirect_to @evidence, notice: 'Evidence was successfully updated.' }
        format.json { render :show, status: :ok, location: @evidence }
      else
        format.html { render :edit }
        format.json { render json: @evidence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /evidences/1
  # DELETE /evidences/1.json
  def destroy
    @evidence.destroy
    respond_to do |format|
      format.html { redirect_to evidences_url, notice: 'Evidence was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evidence
      @evidence = Evidence.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def evidence_params
      params.require(:evidence).permit(:complaint_id, :path_file, :narration)
    end
end

Backend/DenunciaEficiente/app/helpers/evidences_helper.rb
module EvidencesHelper
end

Backend/DenunciaEficiente/app/views/evidences/_form.html.erb
<%= form_with(model: evidence, local: true) do |form| %>
  <% if evidence.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(evidence.errors.count, "error") %> prohibited this evidence from being saved:</h2>

      <ul>
      <% evidence.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :complaint_id %>
    <%= form.text_field :complaint_id %>
  </div>

  <div class="field">
    <%= form.label :path_file %>
    <%= form.text_field :path_file %>
  </div>

  <div class="field">
    <%= form.label :narration %>
    <%= form.text_field :narration %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Backend/DenunciaEficiente/app/views/evidences/edit.html.erb
<h1>Editing Evidence</h1>

<%= render 'form', evidence: @evidence %>

<%= link_to 'Show', @evidence %> |
<%= link_to 'Back', evidences_path %>

Backend/DenunciaEficiente/app/views/evidences/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Evidences</h1>

<table>
  <thead>
    <tr>
      <th>Complaint</th>
      <th>Path file</th>
      <th>Narration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @evidences.each do |evidence| %>
      <tr>
        <td><%= evidence.complaint_id %></td>
        <td><%= evidence.path_file %></td>
        <td><%= evidence.narration %></td>
        <td><%= link_to 'Show', evidence %></td>
        <td><%= link_to 'Edit', edit_evidence_path(evidence) %></td>
        <td><%= link_to 'Destroy', evidence, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Evidence', new_evidence_path %>

Backend/DenunciaEficiente/app/views/evidences/new.html.erb
<h1>New Evidence</h1>

<%= render 'form', evidence: @evidence %>

<%= link_to 'Back', evidences_path %>

Backend/DenunciaEficiente/app/views/evidences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Complaint:</strong>
  <%= @evidence.complaint_id %>
</p>

<p>
  <strong>Path file:</strong>
  <%= @evidence.path_file %>
</p>

<p>
  <strong>Narration:</strong>
  <%= @evidence.narration %>
</p>

<%= link_to 'Edit', edit_evidence_path(@evidence) %> |
<%= link_to 'Back', evidences_path %>